spring:
  application:
    name: SpringJWT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springjwt_db?useSSL=false&useUnicode=true&serverTimezone=America/Toronto&allowPublicKeyRetrieval=true
    username: teo
    password: SM!dyrjsahdi1!


  jpa:
    hibernate:
      ddl-auto: create
      naming:
#        ?? ??? SpringPhysicalNamingStrategy --> camelcase? sneak-case? ???.

#        ?? ??? --> hibernate? ?? ??? ?? ?? ??
#        ??? ?? User => ??? User  /   ?? ?? userName => ?? userName
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # ? ?? ???? Dialect? ????? ??
        format_sql: true
    show-sql: true