spring:
  application:
    name: SpringJWT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springjwt_db?useSSL=false&useUnicode=true&serverTimezone=America/Toronto&allowPublicKeyRetrieval=true
    username: teo
    password: SM!dyrjsahdi1!


  jpa:
    hibernate:
      ddl-auto: update
      naming:
#        ?? ??? SpringPhysicalNamingStrategy --> camelcase? sneak-case? ???.

#        ?? ??? --> hibernate? ?? ??? ?? ?? ??
#        ??? ?? User => ??? User  /   ?? ?? userName => ?? userName
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect # ? ?? ???? Dialect? ????? ??
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB       # 단일 파일 최대 크기
      max-request-size: 100MB   # 전체 요청 최대 크기 (모든 파일 및 폼 데이터 포함)

jwt:
#  base64로 인코딩된 값
  secret: c2RmYmFzZGtnamJzYWRuZndscXB6bWduYmVs
  access-token-expiration-ms: 3600000 # 예: 1시간 (밀리초)
  refresh-token-expiration-ms: 604800000 # 예: 7일 (밀리초)
  token-prefix: Bearer
  header-string: Authorization
